FROM adoptopenjdk/openjdk11-openj9:latest
WORKDIR /work
RUN chmod 777 /work
COPY target/lib /work/lib
COPY target/rest-http-crud-quarkus-1.0.0.Alpha1-SNAPSHOT-runner.jar /work/application.jar
EXPOSE 8080
ENV JAVA_OPTS "$JAVA_OPTS -Djava.net.preferIPv4Stack=true -Xmx128m"
ENTRYPOINT java ${JAVA_OPTS} -cp /work/application -jar /work/application.jar
